version: '3.8'

services:
  app:
    build: .
    container_name: grow-id-backend
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /home/freelance-environment/.env-growid-dev:/var/www/.env
    networks:
      - proxy

  nginx:
    image: nginx:alpine
    container_name: grow-id-nginx
    depends_on:
      - app
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
    expose:
      - ${APP_PORT}

networks:
  proxy:
    external: true
